version: '2.1'
services:
  app:
    image: jpelczar/examhelperserver
    ports:
    - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: sameersbn/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 5s
      timeout: 2s
      retries: 5
    ports:
     - "3306:3306"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    ports:
      - "9200:9200"
      - "9300:9300"